---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      network:
        - [ 'forwarded_port', { guest: 80, host: 8080 } ]

suites:
  - name: default
    run_list:
      - role[qmailtoaster]
